version: '3'

services:

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=struts2crud
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=1234567
      - MYSQL_ROOT_PASSWORD=1234567
    volumes:
      - $HOME/utils/docker/volumes/struts2crud:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
 app-network:
  driver: bridge